name: Build snapshot docker image

on:
  push:
    branches-ignore:
      - main

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
      snapshot-version: ${{ steps.version-step.outputs.version }}
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: extract_branch

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Get source version
        id: version-step
        run: echo "version=$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build API
        run: mvn package --no-transfer-progress -DskipTests=true

      - name: Upload API jar
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: api/target/*.jar

      - name: Upload JMS jar
        uses: actions/upload-artifact@v4
        with:
          name: jms-jar
          path: listener-jms/target/*.jar

  docker-api:
    needs:
      - build-snapshot
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4

      - name: Download uploaded jar
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: api/target/

      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: inseefr/pearl-jam-back-office
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          default_branch: ${{ github.ref }}
          tags: ${{ needs.build-snapshot.outputs.snapshot-version }}
          workdir: api

  docker-jms:
    needs:
      - build-snapshot
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: listener-jms
    steps:
      - uses: actions/checkout@v4

      - name: Download uploaded jar
        uses: actions/download-artifact@v4
        with:
          name: jms-jar
          path: listener-jms/target/

      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: inseefr/pearl-jam-back-office
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          default_branch: ${{ github.ref }}
          tags: ${{ needs.build-snapshot.outputs.snapshot-version }}-jms
          workdir: listener-jms
